//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiHocTap {
    
    
    public partial class CapNhatDiem {
        
        /// <summary>
        /// Menu_Admin1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuanLiHocTap.WUC.Menu_Admin Menu_Admin1;
        
        /// <summary>
        /// CapNhatDiem1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::QuanLiHocTap.WUC.CapNhatDiem CapNhatDiem1;
    }
}
